name: MCModels2
version: '${project.version}'
main: pl.noname.mcmodels2.Main
api-version: '1.15'
commands:
  dajmodel:
    description: add model
    aliases: givemodel
    permission: mcmodls2.givemodel
permissions:
  mcmodels2.givemodel:
    description: add acces to /givemodel command
    default: op